jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Get MySugr Token
      id: mysugrToken
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://eu-prod-api.mysugr.com/rest/v2/users/me/auth/tokens/new'
        method: 'GET'
        username: '${{ secrets.MYSUGR_USER }}'
        password: '${{ secrets.MYSUGR_PASS }}'
    - name: Show Response
        run: |
          echo ${{ steps.lastUpdated.outputs.response }}
          echo ${{ steps.lastUpdated.outputs.headers }}
          echo ${{ fromJson(steps.lastUpdated.outputs.response).userAuthenticationToken.token }}
