name: 1. Get MySugr Access Token
run-name: Get MySugr Access Token (${{ github.ref_name }})
on:
  workflow_dispatch:
  schedule: 
    ## Schedule the job to run every 1st of month 00:00 UTC daily.
    #- cron: '0 0 1 * *'
    
    ## Schedule the job to run every 10th minute.
    - cron: '*/10 * * * *' 

jobs:
  deployment:
    runs-on: ubuntu-latest
    # env:
      # MYSUGR_USER: ${{ secrets.MYSUGR_USER }}
      # MYSUGR_PASS: ${{ secrets.MYSUGR_PASS }}
    outputs:
      MYSUGR_TOKEN: ${{ fromJson(steps.mysugr-token.outputs.response).userAuthenticationToken.token }}
      MYSUGR_USERID: ${{ fromJson(steps.mysugr-token.outputs.response).userAuthenticationToken.userId }}

    steps:
    - name: Get MySugr Token
      id: mysugr-token
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://eu-prod-api.mysugr.com/rest/v2/users/me/auth/tokens/new'
        method: 'GET'
        username: '${{ secrets.MYSUGR_USER }}'
        password: '${{ secrets.MYSUGR_PASS }}'
    - name: Print Result
      run: |
        # show result
        echo ${{ steps.mysugr-token.outputs.response }}
        echo ${{ steps.mysugr-token.outputs.headers }}
