name: get-data
#run-name: Get MySugr Data (${{ github.ref_name }})
on:
  workflow_dispatch:
  #schedule: 
    ## Schedule the job to run every 1st of month 00:00 UTC daily.
    #- cron: '0 0 1 * *'
    
    ## Schedule the job to run every 10th minute.
    #- cron: '*/10 * * * *' 

jobs:
  get-mysugr-data:
    runs-on: ubuntu-latest
#    outputs:
#      MYSUGR_TOKEN: ${{ toJSON(fromJson(steps.mysugr-entries.outputs.response).userAuthenticationToken.token)}}
#      MYSUGR_USERID: ${{ toJSON(fromJson(steps.mysugr-entries.outputs.response).userAuthenticationToken.userId)}}
    permissions: write-all
    
    steps:
    - name: get-mysugr-token
      id: mysugr-token
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://eu-prod-api.mysugr.com/rest/v2/users/me/auth/tokens/new'
        method: 'GET'
        username: '${{ secrets.MYSUGR_USER }}'
        password: '${{ secrets.MYSUGR_PASS }}'

    - name: get-mysugr-entries
      id: mysugr-entries
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://eu-prod-api.mysugr.com/rest/v2/logentries'
        method: 'GET'
        contentType: "application/json"
        username: 'x'
        password: '${{ fromJson(steps.mysugr-token.outputs.response).userAuthenticationToken.token }}'
        customHeaders: '{"If-Modified-Since": "${{ vars.LASTMODIFIED }}"}'

    - name: Update Last Modified Variable
      id: mysugr-last-updated
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.github.com/repos/${{github.repository}}/actions/variables/${{secrets.API_VARIABLE_NAME}}'
        method: 'PATCH'
        bearerToken: '${{ secrets.API_SECRET }}'
        customHeaders: '{"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}'
        data: '{"name":"${{secrets.API_VARIABLE_NAME}}","value":${{ toJSON(fromJson(steps.mysugr-entries.outputs.headers).last-modified)}}}'

